pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=lint-compile-test
      - check-success=e2e-test (firefox)
      - check-success=e2e-test (chrome)
    actions:
      merge:
        method: rebase
