version: "3.3"

services:
  postgres_cph:
    user: ${CURRENT_UID}:${CURRENT_GID}
    build: 
      context: .
      dockerfile: dev.dockerfile 
      args:
        UNAME: ${CURRENT_NAME}
        UID: ${CURRENT_UID}
        GID: ${CURRENT_GID}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql
    volumes:
      - $PWD/data/psql:/var/lib/postgresql/data      
    networks:
      dbnet:
        ipv4_address: 192.168.5.5

  postgres_keycloak:
    user: ${CURRENT_UID}:${CURRENT_GID}
    build: 
      context: .
      dockerfile: dev.dockerfile 
      args:
        UNAME: ${CURRENT_NAME}
        UID: ${CURRENT_UID}
        GID: ${CURRENT_GID}    
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: psql      
    volumes:
      - $PWD/data/keycloak:/var/lib/postgresql/data      
    networks:
      dbnet:
        ipv4_address: 192.168.5.10

  keycloak:
    depends_on:
      - postgres_keycloak
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:    
      DB_VENDOR: postgres
      DB_ADDR: 192.168.5.10
      DB_DATABASE: psql
      DB_USER: psql
      DB_PASSWORD: psql
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin    
    networks:
      - dbnet

networks:
  dbnet:
    ipam:
      config:
        - subnet: 192.168.5.0/24